### PR TITLE
Css brochure form-Laura Grace Manimtim

### PR DESCRIPTION
**Pull request by lauragracem**
Screen Shot 2022-05-11 at 5 33 24 PM

### CODE REVIEW

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
@lauragracem Your form has some differences from the specification image:
- The form heading and submit button should have a redder color.
- The form heading should be a little smaller, relative to the form.
- The form labels should be indented from the left and have a higher font-weight.
- The form controls should be wider.
- The form control borders should be lighter and have rounded corners.
- The `<input>` placeholders should be indented from the left.
- The `<select>` should have more vertical spacing around its content, so its height matches the `<input>`s'.

---

image

---

image

**Comment by lauragracem** [comment]
Screen Shot 2022-05-11 at 6 47 11 PM

**Comment by lauragracem** [comment]
Screen Shot 2022-05-11 at 6 54 32 PM

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
